application:
  image: rahul/ndm:1.0
  volumes:
  - ./:/np-docker-mean
  environment:
    - NODE_ENV=development
  ports:
    - "8085:8085"
  links:
    - mongodb
mongodb:
  image: rahul/mongo:2.0
  ports:
    - "27017:27017"
  volumes:
    - ./DB/data:/data/db
